//! SP1 Guest Program: EVM Transaction Verification Circuit
//!
//! This program runs INSIDE the SP1 STARK prover. It verifies:
//!
//! 1. **Chain continuity**: A keccak256 hash chain links a trusted anchor
//!    block to the target block (variable-length, up to 256 headers)
//! 2. Block header hash matches claimed block hash
//! 3. Transaction is included in the block (Merkle-Patricia Trie proof)
//! 4. Transaction receipt is included in the block (MPT proof)
//! 5. Transaction was successful (receipt.status == 1)
//! 6. Extracts and commits relevant event logs
//!
//! The proof generated by this program proves all of the above without
//! revealing the full block header, transaction, or receipt data to the
//! on-chain verifier.
//!
//! # Security Model
//!
//! - **Chain proof** provides the root of trust: the Solana verifier only
//!   needs to check that the anchor hash matches a governance-maintained
//!   trusted value. The circuit proves the hash chain from anchor → target.
//! - Forging a chain proof requires a keccak256 preimage attack (~2^256)
//! - Transaction MPT proof proves inclusion in the target block
//! - Receipt MPT proof proves execution result
//! - Event logs prove specific contract interactions (e.g., USDC lock)
//!
//! # Compute Cost
//!
//! Guest execution is off-chain and free. The on-chain verification of the
//! resulting STARK proof costs ~500k compute units on Solana.

#![no_main]
sp1_zkvm::entrypoint!(main);

use tiny_keccak::{Hasher, Keccak};
use x0_sp1_evm_common::{
    EVMProofPublicInputs, EVMProofWitness, EventLog,
    MAX_MPT_PROOF_DEPTH, MAX_BLOCK_HEADER_RLP_SIZE,
    MAX_TRANSACTION_RLP_SIZE, MAX_RECEIPT_RLP_SIZE,
    MAX_CHAIN_PROOF_DEPTH,
};

pub fn main() {
    // ========================================================================
    // Step 1: Read private inputs (witness)
    // ========================================================================

    let witness: EVMProofWitness = sp1_zkvm::io::read();

    // ========================================================================
    // Step 1b: Validate witness bounds (defense-in-depth)
    //
    // These checks bound the circuit's input size, preventing a malicious
    // host from supplying adversarial data that bloats cycle count or
    // triggers unbounded memory allocation inside the zkVM.
    // ========================================================================

    assert!(
        witness.block_hash != [0u8; 32],
        "Block hash must not be zero"
    );
    assert!(
        !witness.block_header_rlp.is_empty(),
        "Block header RLP must not be empty"
    );
    assert!(
        witness.block_header_rlp.len() <= MAX_BLOCK_HEADER_RLP_SIZE,
        "Block header RLP exceeds max size"
    );
    assert!(
        !witness.transaction_rlp.is_empty(),
        "Transaction RLP must not be empty"
    );
    assert!(
        witness.transaction_rlp.len() <= MAX_TRANSACTION_RLP_SIZE,
        "Transaction RLP exceeds max size"
    );
    assert!(
        !witness.receipt_rlp.is_empty(),
        "Receipt RLP must not be empty"
    );
    assert!(
        witness.receipt_rlp.len() <= MAX_RECEIPT_RLP_SIZE,
        "Receipt RLP exceeds max size"
    );
    assert!(
        witness.tx_proof_nodes.len() <= MAX_MPT_PROOF_DEPTH,
        "Transaction MPT proof exceeds max depth"
    );
    assert!(
        witness.receipt_proof_nodes.len() <= MAX_MPT_PROOF_DEPTH,
        "Receipt MPT proof exceeds max depth"
    );

    // Chain proof bounds
    assert!(
        witness.chain_proof.headers.len() >= 2,
        "Chain proof must have at least 2 headers (anchor + target)"
    );
    assert!(
        witness.chain_proof.headers.len() <= MAX_CHAIN_PROOF_DEPTH,
        "Chain proof exceeds max depth"
    );
    for header in &witness.chain_proof.headers {
        assert!(
            !header.rlp_encoded.is_empty(),
            "Chain proof header has empty RLP"
        );
        assert!(
            header.rlp_encoded.len() <= MAX_BLOCK_HEADER_RLP_SIZE,
            "Chain proof header RLP exceeds max size"
        );
    }

    // ========================================================================
    // Step 2: Verify chain proof (anchor → target)
    //
    // This is the root of trust. We verify a keccak256 hash chain from
    // the anchor block to the target block. The Solana verifier only needs
    // to check that the anchor hash matches a trusted governance value.
    //
    // For each consecutive pair (i-1, i):
    //   1. keccak256(headers[i-1].rlp) must equal headers[i].parent_hash
    //   2. Block numbers must be sequential
    //
    // This makes forging a chain computationally infeasible (~2^256).
    // ========================================================================

    let chain = &witness.chain_proof;
    let chain_len = chain.headers.len();

    // Compute and verify ALL block hashes
    let mut chain_hashes: Vec<[u8; 32]> = Vec::with_capacity(chain_len);
    for header in &chain.headers {
        chain_hashes.push(keccak256(&header.rlp_encoded));
    }

    // Verify parent_hash linkage and block number sequentiality
    for i in 1..chain_len {
        let prev_hash = chain_hashes[i - 1];
        assert_eq!(
            prev_hash,
            chain.headers[i].parent_hash,
            "Chain broken between block {} and {}: parent_hash mismatch",
            chain.headers[i - 1].number,
            chain.headers[i].number,
        );
        assert_eq!(
            chain.headers[i].number,
            chain.headers[i - 1].number + 1,
            "Block numbers not sequential: {} followed by {}",
            chain.headers[i - 1].number,
            chain.headers[i].number,
        );
    }

    // Extract anchor (first) and target (last) from the verified chain
    let anchor_hash = chain_hashes[0];
    let anchor_block = chain.headers[0].number;
    let target_hash = chain_hashes[chain_len - 1];
    let target_header = &chain.headers[chain_len - 1];

    // Verify target block matches the witness block
    assert_eq!(
        target_hash, witness.block_hash,
        "Chain proof target hash does not match witness block_hash"
    );
    assert_eq!(
        target_header.rlp_encoded, witness.block_header_rlp,
        "Chain proof target RLP does not match witness block_header_rlp"
    );
    assert_eq!(
        target_header.number, witness.block_number,
        "Chain proof target number does not match witness block_number"
    );

    // Verify the anchor's parent_hash field matches what's in the RLP
    // (defense-in-depth: the `parent_hash` struct field must match the RLP)
    let anchor_items = rlp_decode_list(&chain.headers[0].rlp_encoded);
    assert!(
        anchor_items.len() > 0,
        "Anchor block header has no fields"
    );
    let anchor_parent_hash_from_rlp = extract_bytes32(&anchor_items[0]);
    assert_eq!(
        chain.headers[0].parent_hash, anchor_parent_hash_from_rlp,
        "Anchor parent_hash field does not match RLP content"
    );

    // ========================================================================
    // Step 3: Extract roots from block header
    //
    // The target block header hash was already verified by the chain proof.
    // Now extract the trie roots for MPT verification.
    //
    // RLP block header structure (relevant fields):
    //   [0]  parentHash
    //   [1]  ommersHash
    //   [2]  beneficiary
    //   [3]  stateRoot
    //   [4]  transactionsRoot  ← we need this
    //   [5]  receiptsRoot      ← we need this
    //   ...
    // ========================================================================

    let header_items = rlp_decode_list(&witness.block_header_rlp);

    // Extract transactionsRoot (field index 4)
    assert!(
        header_items.len() > 5,
        "Block header has too few fields"
    );
    let transactions_root = extract_bytes32(&header_items[4]);

    // Extract receiptsRoot (field index 5)
    let receipts_root = extract_bytes32(&header_items[5]);

    // ========================================================================
    // Step 4: Verify transaction inclusion (MPT proof)
    //
    // Prove that the transaction exists in the block's transaction trie.
    // The key is the RLP-encoded transaction index.
    // ========================================================================

    let tx_key = rlp_encode_u32(witness.transaction_index);

    assert!(
        verify_mpt_proof(
            &transactions_root,
            &tx_key,
            &witness.transaction_rlp,
            &witness.tx_proof_nodes,
        ),
        "Transaction MPT proof verification failed"
    );

    // ========================================================================
    // Step 5: Verify receipt inclusion (MPT proof)
    //
    // Prove that the receipt exists in the block's receipt trie.
    // The key is the same RLP-encoded transaction index.
    // ========================================================================

    assert!(
        verify_mpt_proof(
            &receipts_root,
            &tx_key,
            &witness.receipt_rlp,
            &witness.receipt_proof_nodes,
        ),
        "Receipt MPT proof verification failed"
    );

    // ========================================================================
    // Step 6: Parse receipt and verify success
    // ========================================================================

    // For Type 2 (EIP-1559) transactions, the receipt is prefixed with 0x02
    // We handle both legacy and typed receipts
    let (status, logs_rlp) = parse_receipt(&witness.receipt_rlp);

    assert_eq!(status, 1, "Transaction receipt status is not success");

    // ========================================================================
    // Step 7: Extract event logs (with optional filtering)
    // ========================================================================

    let event_logs = extract_event_logs(
        &logs_rlp,
        &witness.relevant_contracts,
        &witness.relevant_topics,
    );

    // ========================================================================
    // Step 8: Commit public outputs
    //
    // These values will be available to the Solana verifier after proof
    // verification. They are cryptographically bound to the proof.
    // ========================================================================

    let public_inputs = EVMProofPublicInputs {
        block_hash: witness.block_hash,
        block_number: witness.block_number,
        tx_hash: keccak256(&witness.transaction_rlp),
        from: witness.from,
        to: witness.to,
        value: witness.value,
        success: true,
        event_logs,

        // Chain proof anchor — verified on-chain against trusted state
        chain_anchor_block: anchor_block,
        chain_anchor_hash: anchor_hash,
    };

    // Borsh-serialize for Solana compatibility
    let serialized = borsh::to_vec(&public_inputs)
        .expect("Failed to serialize public inputs");

    sp1_zkvm::io::commit_slice(&serialized);
}

// ============================================================================
// Cryptographic Helpers
// ============================================================================

/// Compute keccak256 hash
fn keccak256(data: &[u8]) -> [u8; 32] {
    let mut hasher = Keccak::v256();
    let mut output = [0u8; 32];
    hasher.update(data);
    hasher.finalize(&mut output);
    output
}

// ============================================================================
// RLP Helpers
// ============================================================================

/// Decode an RLP list into its items (raw byte slices)
///
/// Returns the byte ranges of each item in the list.
fn rlp_decode_list(data: &[u8]) -> Vec<&[u8]> {
    let mut items = Vec::new();

    if data.is_empty() {
        return items;
    }

    // Check for typed transaction/receipt prefix (EIP-2718: any byte < 0x80 and != 0x00
    // is a transaction type byte, covering EIP-2930 (0x01), EIP-1559 (0x02),
    // EIP-4844 (0x03), EIP-7702 (0x04), and future types)
    let start = if data[0] < 0x80 && data[0] != 0x00 {
        1 // Skip type byte
    } else {
        0
    };

    // Decode list header
    let (list_data, _) = decode_rlp_item(&data[start..]);

    let mut inner_pos = 0;
    while inner_pos < list_data.len() {
        let (item, consumed) = decode_rlp_item(&list_data[inner_pos..]);
        items.push(item);
        inner_pos += consumed;
    }

    items
}

/// Decode a single RLP item, returning the data and total bytes consumed
fn decode_rlp_item(data: &[u8]) -> (&[u8], usize) {
    if data.is_empty() {
        return (&[], 0);
    }

    let prefix = data[0];

    if prefix < 0x80 {
        // Single byte
        (&data[0..1], 1)
    } else if prefix <= 0xb7 {
        // Short string (0-55 bytes)
        let len = (prefix - 0x80) as usize;
        (&data[1..1 + len], 1 + len)
    } else if prefix <= 0xbf {
        // Long string
        let len_bytes = (prefix - 0xb7) as usize;
        let len = decode_length(&data[1..1 + len_bytes]);
        (&data[1 + len_bytes..1 + len_bytes + len], 1 + len_bytes + len)
    } else if prefix <= 0xf7 {
        // Short list (0-55 bytes total)
        let len = (prefix - 0xc0) as usize;
        (&data[1..1 + len], 1 + len)
    } else {
        // Long list
        let len_bytes = (prefix - 0xf7) as usize;
        let len = decode_length(&data[1..1 + len_bytes]);
        (&data[1 + len_bytes..1 + len_bytes + len], 1 + len_bytes + len)
    }
}

/// Decode a big-endian length from bytes
fn decode_length(data: &[u8]) -> usize {
    let mut length = 0usize;
    for &byte in data {
        length = (length << 8) | (byte as usize);
    }
    length
}

/// Extract a 32-byte value from an RLP-decoded item
fn extract_bytes32(data: &[u8]) -> [u8; 32] {
    let mut result = [0u8; 32];
    if data.len() >= 32 {
        result.copy_from_slice(&data[..32]);
    } else {
        // Left-pad with zeros for shorter values
        let offset = 32 - data.len();
        result[offset..].copy_from_slice(data);
    }
    result
}

/// RLP-encode a u32 (for transaction index key)
///
/// Per the Ethereum Yellow Paper, the trie key for transaction/receipt
/// at index `i` is `RLP(i)`. For index 0, this is `0x80` (RLP empty
/// string), which is correct — verified against go-ethereum's behavior.
fn rlp_encode_u32(value: u32) -> Vec<u8> {
    if value == 0 {
        // RLP(0) = 0x80 — the empty byte string.
        // This matches how Ethereum encodes tx index 0 in the trie.
        return vec![0x80];
    }
    let bytes = value.to_be_bytes();
    let start = bytes.iter().position(|&b| b != 0).unwrap_or(3);
    let significant = &bytes[start..];

    if significant.len() == 1 && significant[0] < 0x80 {
        significant.to_vec()
    } else {
        let mut encoded = vec![0x80 + significant.len() as u8];
        encoded.extend_from_slice(significant);
        encoded
    }
}

// ============================================================================
// Merkle-Patricia Trie (MPT) Proof Verification
//
// NOTE ON DUPLICATION: The host (artifacts.rs) has a `SimpleMPT` builder and
// the guest (here) has a `verify_mpt_proof` verifier. They are intentionally
// separate because the guest runs in a `no_std` SP1 zkVM environment and
// cannot share crates with the host. The two implementations stay consistent
// via the host-side cross-validation in `construct_proofs`: after building the
// trie with `SimpleMPT`, the host recomputes the root and asserts it equals
// the block header's `transactions_root` / `receipts_root` before the witness
// is submitted to the prover. Any divergence in encoding would be caught at
// proof-generation time, not silently at verification.
// ============================================================================

/// Verify a Merkle-Patricia Trie proof
///
/// Proves that a key-value pair exists in a trie with the given root hash.
///
/// # Arguments
/// * `root` - Expected trie root hash (from block header)
/// * `key` - RLP-encoded key (transaction index)
/// * `value` - Expected value (RLP-encoded transaction or receipt)
/// * `proof_nodes` - Trie nodes from root to leaf
fn verify_mpt_proof(
    root: &[u8; 32],
    key: &[u8],
    value: &[u8],
    proof_nodes: &[Vec<u8>],
) -> bool {
    if proof_nodes.is_empty() {
        return false;
    }

    // Verify the root node matches. For nodes < 32 bytes (inline nodes),
    // Ethereum embeds them directly rather than their keccak256 hash.
    // Comparing the hash of a short node would always fail for such tries.
    if proof_nodes[0].len() < 32 {
        // Inline root: compare raw content to root bytes
        if proof_nodes[0].as_slice() != root.as_slice() {
            return false;
        }
    } else {
        let first_node_hash = keccak256(&proof_nodes[0]);
        if first_node_hash != *root {
            return false;
        }
    }

    // Convert key to nibbles for trie traversal
    let key_nibbles = bytes_to_nibbles(key);
    let mut key_pos = 0;

    for (i, node) in proof_nodes.iter().enumerate() {
        let items = rlp_decode_list(node);
        let is_last = i == proof_nodes.len() - 1;

        match items.len() {
            17 => {
                // Branch node: 16 children + value
                if is_last {
                    // Value should be at the branch's value slot
                    if key_pos == key_nibbles.len() {
                        return items[16] == value;
                    }
                } else if key_pos < key_nibbles.len() {
                    // Follow the child at the current nibble
                    let nibble = key_nibbles[key_pos] as usize;
                    let child = items[nibble];

                    // Verify next node matches this child reference
                    if i + 1 < proof_nodes.len() {
                        if child.len() == 32 {
                            // External node: child is the keccak256 hash
                            let mut h = [0u8; 32];
                            h.copy_from_slice(child);
                            let next_hash = keccak256(&proof_nodes[i + 1]);
                            if h != next_hash {
                                return false;
                            }
                        } else if !child.is_empty() {
                            // Inline node: child content is embedded directly
                            // in the parent node's RLP. The parent's hash
                            // already covers this data. Verify that the next
                            // proof node decodes to matching content.
                            let (decoded_next, _) = decode_rlp_item(&proof_nodes[i + 1]);
                            if decoded_next != child {
                                return false;
                            }
                        } else {
                            // Empty child slot — shouldn't be following this path
                            return false;
                        }
                    }
                    key_pos += 1;
                }
            }
            2 => {
                // Extension or Leaf node
                let path = decode_compact_path(items[0]);
                let is_leaf = path.0;
                let nibbles = path.1;

                // Verify path matches
                if key_pos + nibbles.len() > key_nibbles.len() {
                    return false;
                }
                if key_nibbles[key_pos..key_pos + nibbles.len()] != nibbles[..] {
                    return false;
                }
                key_pos += nibbles.len();

                if is_leaf && is_last {
                    // Leaf node: value should match
                    return items[1] == value;
                } else if !is_leaf && !is_last {
                    // Extension node: verify next node reference
                    if i + 1 < proof_nodes.len() {
                        if items[1].len() == 32 {
                            // External node: child reference is a keccak256 hash
                            let mut h = [0u8; 32];
                            h.copy_from_slice(items[1]);
                            let next_hash = keccak256(&proof_nodes[i + 1]);
                            if h != next_hash {
                                return false;
                            }
                        } else if !items[1].is_empty() {
                            // Inline node: child content is embedded directly.
                            // Verify next proof node decodes to matching content.
                            let (decoded_next, _) = decode_rlp_item(&proof_nodes[i + 1]);
                            if decoded_next != items[1] {
                                return false;
                            }
                        }
                    }
                }
            }
            _ => return false,
        }
    }

    true
}

/// Convert bytes to nibbles (each byte → 2 nibbles)
fn bytes_to_nibbles(data: &[u8]) -> Vec<u8> {
    let mut nibbles = Vec::with_capacity(data.len() * 2);
    for &byte in data {
        nibbles.push(byte >> 4);
        nibbles.push(byte & 0x0f);
    }
    nibbles
}

/// Decode compact (hex prefix) encoded path
/// Returns (is_leaf, nibbles)
fn decode_compact_path(data: &[u8]) -> (bool, Vec<u8>) {
    if data.is_empty() {
        return (false, Vec::new());
    }

    let first = data[0];
    let is_leaf = first >= 0x20;
    let has_odd_length = (first & 0x10) != 0;

    let mut nibbles = Vec::new();

    if has_odd_length {
        nibbles.push(first & 0x0f);
    }

    for &byte in &data[1..] {
        nibbles.push(byte >> 4);
        nibbles.push(byte & 0x0f);
    }

    (is_leaf, nibbles)
}

// ============================================================================
// Receipt Parsing
// ============================================================================

/// Parse a transaction receipt, handling both legacy and typed receipts
///
/// Returns (status, logs_rlp_bytes)
fn parse_receipt(receipt_rlp: &[u8]) -> (u8, Vec<u8>) {
    // Use the same consistent rule as rlp_decode_list: any single byte
    // below the RLP string range (< 0x80, non-zero) is an EIP-2718 type
    // prefix. This handles type 0x01, 0x02, 0x03, 0x04 (EIP-7702) and
    // any future typed receipt without needing to enumerate every type.
    let data = if !receipt_rlp.is_empty() && receipt_rlp[0] < 0x80 && receipt_rlp[0] != 0x00 {
        // Typed receipt: skip type byte
        &receipt_rlp[1..]
    } else {
        receipt_rlp
    };

    let items = rlp_decode_list(data);

    // Receipt fields:
    //   [0] status (post-Byzantium) or state root (pre-Byzantium)
    //   [1] cumulativeGasUsed
    //   [2] logsBloom
    //   [3] logs

    if items.len() < 4 {
        return (0, Vec::new());
    }

    let status = if items[0].len() == 1 {
        items[0][0]
    } else if items[0].is_empty() {
        0
    } else {
        // Pre-Byzantium receipts have a 32-byte state root instead of a
        // 1-byte status code. Base launched post-Byzantium (2021), so
        // pre-Byzantium receipts should NEVER appear on Base.
        //
        // If we encounter one, the receipt is either:
        // 1. Malformed/forged (attack)
        // 2. Targeting the wrong chain
        //
        // Reject unconditionally rather than guessing success.
        panic!(
            "Pre-Byzantium receipt format detected (state root {} bytes). \
             Base is a post-Byzantium chain — this receipt is invalid.",
            items[0].len()
        )
    };

    (status, items[3].to_vec())
}

/// Extract event logs from the RLP-encoded logs list, filtered by
/// contract address and event topic signature.
///
/// If `relevant_contracts` is empty, all contracts pass.
/// If `relevant_topics` is empty, all topics pass.
fn extract_event_logs(
    logs_rlp: &[u8],
    relevant_contracts: &[[u8; 20]],
    relevant_topics: &[[u8; 32]],
) -> Vec<EventLog> {
    let log_items = rlp_decode_list(logs_rlp);
    let mut events = Vec::new();

    for log_rlp in log_items {
        let log_fields = rlp_decode_list(log_rlp);
        if log_fields.len() < 3 {
            continue;
        }

        // Log fields: [address, topics, data]
        let mut contract_address = [0u8; 20];
        if log_fields[0].len() >= 20 {
            contract_address.copy_from_slice(&log_fields[0][..20]);
        }

        // Filter by contract address
        if !relevant_contracts.is_empty()
            && !relevant_contracts.contains(&contract_address)
        {
            continue;
        }

        let topic_items = rlp_decode_list(log_fields[1]);
        let topics: Vec<[u8; 32]> = topic_items
            .iter()
            .map(|t| extract_bytes32(t))
            .collect();

        // Filter by event topic signature (topics[0])
        if !relevant_topics.is_empty()
            && (topics.is_empty() || !relevant_topics.contains(&topics[0]))
        {
            continue;
        }

        events.push(EventLog {
            contract_address,
            topics,
            data: log_fields[2].to_vec(),
        });
    }

    events
}
